name: Github Actions Demo
on:
    repository_dispatch:
        types: [dispatch-test]
    workflow_dispatch:
jobs:
    actions-demo:
        runs-on: ubuntu-latest
        env:
            TEXT: ${{ inputs.text }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v3
            - run: go run actions/actions.go
